import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pawan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1"
        />
      </head>
      <body className={inter.className}>
        <div>
          <Provider>
            <Navbar />
            <main className="dark:bg-page-gradient pt-[10rem]">
              <div className="dark:bg-page-gradient background-gradient fixed inset-0 -z-50 max-h-screen" />
              {children}
            </main>
            <Footer />
          </Provider>

        </div>


      </body>
    </html>
  );
}
